version: "2"
checks:
    argument-count:
        config:
            threshold: 6
    file-lines:
        config:
            threshold: 300
    method-complexity:
        config:
            threshold: 8
    method-lines:
        config:
            threshold: 30