#!/usr/bin/env python3

from smrf.framework.model_framework import run_smrf
import argparse
import os
import sys

def run():
    '''
    run_smrf is a command line program meant to take a single
    argument for the config file.  From this program, smrf.framework
    will be loaded to run the full program.

    Users can also run the model as they want by using the smrf.framework.SMRF
    class to change things or whatever
    '''
    parser = argparse.ArgumentParser(description='Examines SMRF config files for issues.')
    parser.add_argument('config_file', metavar='F', type=str,
                        help='Path to SMRF config file to run')

    args = parser.parse_args()

    if os.path.isfile(args.config_file):
        run_smrf(args.config_file)

    else:
        raise IOError('File does not exist.')


if __name__ == '__main__':
    run()
