#!/usr/bin/env bash

# A script to create the gold files needed for SMRF
# Run this script in the main smrf directory, the config
# file will put the outputs in the correct place
#
# Run as:
#     $ ./tests/basins/RME/gold/make_gold_stations

read -r -p "Recreating gold standard, are you sure? [y/N] " response
if [[ "$response" = "yes" || "$response" = "y" ]]
then
    echo "Updating RME station gold files"
    echo "Removing old gold files"
    rm tests/basins/RME/gold/*.nc

    echo "Running SMRF"
    run_smrf tests/basins/RME/gold/gold_config.ini

    if [ $? == 0 ]; then
        echo "Cleaning up"
        rm tests/basins/RME/gold/log.txt
        rm tests/basins/RME/gold/config.ini
        rm -rf tests/basins/RME/gold/input_backup
    fi
else
    echo "RME station gold files not updated"
fi

